### ISSUE TITLE
android?

### ISSUE THREAD

**Issue by djhashh** [hdmamin/jabberwocky#1]
Hi, ive been really wanting to try jabberwocky for a while now..problem is...i dont have a cpu..lame, i know..i have an android phone and im running termux for some stuff.. what would it take for me to somehow port this over to android/termex/vps? Sorry..  btw i have an api beta key

**Comment by hdmamin** [comment]
I have no experience with android or termux but I'm guessing it would require some pretty major changes - the speech recognition package jabberwocky uses is "not designed to work on mobile devices" [according to its creator](https://github.com/Uberi/speech_recognition/issues/260) and I'm also using the built-in text to speech functionality from OS X.  You might have better luck looking for a GPT-3-based Alexa skill since (I think) that's compatible with android.
